<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9STO36a\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9STO36a/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9STO36a.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9STO36a\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container9STO36a\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '9STO36a',
    'container.build_id' => '7af3e1e1',
    'container.build_time' => 1668152219,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9STO36a');
